### ISSUE TITLE
Indendation rule ?

### ISSUE THREAD

**Issue by maxiiss** [osullivryan/vscode-lsdyna#10]
Hello @osullivryan, 

First of all thank you for your work. As you can have seen I added some keywords to your work (btw : thanks for the validation of the pull request). 
I would like to add some new keywords (I have read your new Readme.md) but before adding more, I was wondering what was the indentation logic you have used for the question mark. For example, one of your commit is : 
```fortran
*DATABASE_DISBOUT
$#      dt    binary      lcur     ioopt
         ?         2
$

``` 

So the user should add 2 digits in "dt" to match the lsdyna format : 

![image](https://user-images.githubusercontent.com/10705263/88651021-8bc26c00-d0c9-11ea-97d6-847c0c7bd639.png)

Is it your global rule ? 

I would like to open the discussion about it, in order to standardize the rule for future Pull Requests.

Best regards.

**Comment by osullivryan** [comment]
@maxiiss ,

Thanks for the ticket. I actually think you have found a bug that happens when converting from the `?` format. I will look in to this tonight and get back to you.
